# Generated by Django 5.2.10 on 2026-01-30 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(default='', max_length=100)),
                ('field2', models.IntegerField(blank=True, default=0, null=True)),
                ('field3', models.DecimalField(decimal_places=2, default=0, help_text='Help text here', max_digits=10, verbose_name='Field 3')),
            ],
            options={
                'verbose_name': 'Example Model',
                'verbose_name_plural': 'Example Models',
            },
        ),
        migrations.CreateModel(
            name='ExampleModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreignKeyField', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.examplemodel', verbose_name='Example')),
            ],
        ),
    ]
