# Generated by Django 5.2.10 on 2026-03-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(default='Adam', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(default='Walsh', max_length=25),
            preserve_default=False,
        ),
    ]
