# Generated by Django 5.2.10 on 2026-02-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_trust_last_updated_events_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='title',
        ),
    ]
