# Generated by Django 5.2.10 on 2026-03-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_f_name_profile_l_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_bio',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='l_name',
        ),
    ]
