# Generated by Django 5.2.10 on 2026-03-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_events_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='bio',
            new_name='descirption',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('taken', 'Taken')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('taken', 'Taken')], default='available', max_length=50),
        ),
    ]
