# Generated by Django 5.2.10 on 2026-03-09 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image_item_photo_remove_listing_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.address'),
        ),
        migrations.AlterField(
            model_name='savedlisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.DeleteModel(
            name='SavedAssociation',
        ),
    ]
