# Generated by Django 5.2.10 on 2026-03-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_events_address_alter_savedlisting_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='event_images/'),
        ),
        migrations.DeleteModel(
            name='ItemProfileAssociation',
        ),
    ]
