# Generated by Django 5.2.10 on 2026-03-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_events_photo_delete_itemprofileassociation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventProfileAssociation',
            new_name='EventSignUp',
        ),
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together={('event', 'user')},
        ),
    ]
