# Generated by Django 5.2.10 on 2026-03-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_eventprofileassociation_eventsignup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel2',
            name='foreignKeyField',
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.DeleteModel(
            name='ExampleModel2',
        ),
    ]
