# Generated by Django 5.2.10 on 2026-03-25 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_examplemodel2_foreignkeyfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transaction'),
        ),
    ]
